default: &default
  adapter: postgresql
  username: postgres
  password:
  encoding: unicode
  pool: 20
  schema_search_path: public

development:
  <<: *default
  database: ansel_dev
  host: localhost

test:
  <<: *default
  database: ansel_test
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
